version: '3.7'
services:
    postgres:
        image: postgres:10.5
        container_name: postgresDB
        restart: always
        environment:
          - POSTGRES_DB=db
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=password
        ports:
          - '5432:5432'
        volumes:
          - ./migrations:/docker-entrypoint-initdb.d